---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: countapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: countapp
  template:
    metadata:
      labels:
        app: countapp
    spec:
      affinity:
        # ⬇⬇⬇ This ensures pods will land on separate hosts
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions: [{ key: app, operator: In, values: [hello] }]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hello
        image: nginxdemos/countapp:latest
        ports:
          - name: http
            containerPort: 80
      terminationGracePeriodSeconds: 1

